### ISSUE TITLE
How to flash the nano?

### ISSUE THREAD

**Issue by nadavmatalon** [orobardet/klipper_nano_expander#1]
Hi,
Thank you very much for making this available!
I understand the hardware part, but are there specific instructions on how to flash the nano to become a klipper secondary mcu?

**Comment by orobardet** [comment]
Hi.

I just committed with a new section [Flashing firmware](https://github.com/orobardet/klipper_nano_expander#flashing-firmware), and more information in the "Software configuration" section.  
This should help with flashing Klipper into the nano expander and use it as a secondary MCU.

**Comment by nadavmatalon** [comment]
That brilliant, thank you very much!
